<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>charls_dotnet_benchmark</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <SubsystemVersion>6.04</SubsystemVersion> <!-- Target Windows 11 and Windows Server 2022 and newer -->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
    <PackageReference Include="BenchmarkDotNet.Diagnostics.dotTrace" />
    <PackageReference Include="CharLS.Native" />
    <PackageReference Include="CharLS.Managed" />
    <PackageReference Include="cscharls" />
  </ItemGroup>

</Project>
